///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AsesorEnLineaAndroid
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the AsesorEnLineaAndroidRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("6dce7644-ba05-4926-bd0f-a29c8d1e9ecd")]
    public partial class AsesorEnLineaAndroidRepository : RepoGenBaseFolder
    {
        static AsesorEnLineaAndroidRepository instance = new AsesorEnLineaAndroidRepository();
        AsesorEnLineaAndroidRepositoryFolders.ComProteccionVideoasesoriaAppFolder _comproteccionvideoasesoria;

        /// <summary>
        /// Gets the singleton class instance representing the AsesorEnLineaAndroidRepository element repository.
        /// </summary>
        [RepositoryFolder("6dce7644-ba05-4926-bd0f-a29c8d1e9ecd")]
        public static AsesorEnLineaAndroidRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public AsesorEnLineaAndroidRepository() 
            : base("AsesorEnLineaAndroidRepository", "/", null, 0, false, "6dce7644-ba05-4926-bd0f-a29c8d1e9ecd", ".\\RepositoryImages\\AsesorEnLineaAndroidRepository6dce7644.rximgres")
        {
            _comproteccionvideoasesoria = new AsesorEnLineaAndroidRepositoryFolders.ComProteccionVideoasesoriaAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("6dce7644-ba05-4926-bd0f-a29c8d1e9ecd")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ComProteccionVideoasesoria folder.
        /// </summary>
        [RepositoryFolder("da65db42-daa7-44f9-8269-a0672e534c05")]
        public virtual AsesorEnLineaAndroidRepositoryFolders.ComProteccionVideoasesoriaAppFolder ComProteccionVideoasesoria
        {
            get { return _comproteccionvideoasesoria; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class AsesorEnLineaAndroidRepositoryFolders
    {
        /// <summary>
        /// The ComProteccionVideoasesoriaAppFolder folder.
        /// </summary>
        [RepositoryFolder("da65db42-daa7-44f9-8269-a0672e534c05")]
        public partial class ComProteccionVideoasesoriaAppFolder : RepoGenBaseFolder
        {
            AsesorEnLineaAndroidRepositoryFolders.LoginFolder _login;
            AsesorEnLineaAndroidRepositoryFolders.CerrarSesionFolder _cerrarsesion;
            AsesorEnLineaAndroidRepositoryFolders.AsignarCitaFolder _asignarcita;
            AsesorEnLineaAndroidRepositoryFolders.ReasignarCitaFolder _reasignarcita;
            AsesorEnLineaAndroidRepositoryFolders.EliminarCitaFolder _eliminarcita;

            /// <summary>
            /// Creates a new ComProteccionVideoasesoria  folder.
            /// </summary>
            public ComProteccionVideoasesoriaAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ComProteccionVideoasesoria", "/mobileapp[@title='com.proteccion.videoasesoria']", parentFolder, 30000, null, false, "da65db42-daa7-44f9-8269-a0672e534c05", "")
            {
                _login = new AsesorEnLineaAndroidRepositoryFolders.LoginFolder(this);
                _cerrarsesion = new AsesorEnLineaAndroidRepositoryFolders.CerrarSesionFolder(this);
                _asignarcita = new AsesorEnLineaAndroidRepositoryFolders.AsignarCitaFolder(this);
                _reasignarcita = new AsesorEnLineaAndroidRepositoryFolders.ReasignarCitaFolder(this);
                _eliminarcita = new AsesorEnLineaAndroidRepositoryFolders.EliminarCitaFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("da65db42-daa7-44f9-8269-a0672e534c05")]
            public virtual Ranorex.MobileApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MobileApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("da65db42-daa7-44f9-8269-a0672e534c05")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Login folder.
            /// </summary>
            [RepositoryFolder("f1d07b69-b62e-446a-9ea6-7c7019e30d3e")]
            public virtual AsesorEnLineaAndroidRepositoryFolders.LoginFolder Login
            {
                get { return _login; }
            }

            /// <summary>
            /// The CerrarSesion folder.
            /// </summary>
            [RepositoryFolder("61b58625-db67-4f9d-9dd1-ed80412a87f9")]
            public virtual AsesorEnLineaAndroidRepositoryFolders.CerrarSesionFolder CerrarSesion
            {
                get { return _cerrarsesion; }
            }

            /// <summary>
            /// The AsignarCita folder.
            /// </summary>
            [RepositoryFolder("db09b4e7-a812-4fc9-9f65-f52e7d80dd0e")]
            public virtual AsesorEnLineaAndroidRepositoryFolders.AsignarCitaFolder AsignarCita
            {
                get { return _asignarcita; }
            }

            /// <summary>
            /// The ReasignarCita folder.
            /// </summary>
            [RepositoryFolder("6ef510b0-d838-486b-ba36-257411c55bce")]
            public virtual AsesorEnLineaAndroidRepositoryFolders.ReasignarCitaFolder ReasignarCita
            {
                get { return _reasignarcita; }
            }

            /// <summary>
            /// The EliminarCita folder.
            /// </summary>
            [RepositoryFolder("1786513e-6ce3-4984-92f0-b5cb5345d266")]
            public virtual AsesorEnLineaAndroidRepositoryFolders.EliminarCitaFolder EliminarCita
            {
                get { return _eliminarcita; }
            }
        }

        /// <summary>
        /// The LoginFolder folder.
        /// </summary>
        [RepositoryFolder("f1d07b69-b62e-446a-9ea6-7c7019e30d3e")]
        public partial class LoginFolder : RepoGenBaseFolder
        {
            AsesorEnLineaAndroidRepositoryFolders.ContentFolder _content;
            RepoItemInfo _ceduladeciudadaniaInfo;
            RepoItemInfo _pruebasyeraldinInfo;

            /// <summary>
            /// Creates a new Login  folder.
            /// </summary>
            public LoginFolder(RepoGenBaseFolder parentFolder) :
                    base("Login", "", parentFolder, 30000, null, false, "f1d07b69-b62e-446a-9ea6-7c7019e30d3e", "")
            {
                _content = new AsesorEnLineaAndroidRepositoryFolders.ContentFolder(this);
                _ceduladeciudadaniaInfo = new RepoItemInfo(this, "CedulaDeCiudadania", "form[@title='(none)']/androidelement/androidelement/text[2]", 30000, null, "2a0146fb-9200-4ef3-a46c-4e814ad0025c");
                _pruebasyeraldinInfo = new RepoItemInfo(this, "PruebasYeraldin", "form[@title='(none)']/androidelement/androidelement/text[5]", 30000, null, "43c405d2-5f59-4145-a96e-16f8b2058a1e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f1d07b69-b62e-446a-9ea6-7c7019e30d3e")]
            public virtual Ranorex.MobileApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MobileApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f1d07b69-b62e-446a-9ea6-7c7019e30d3e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CedulaDeCiudadania item.
            /// </summary>
            [RepositoryItem("2a0146fb-9200-4ef3-a46c-4e814ad0025c")]
            public virtual Ranorex.Text CedulaDeCiudadania
            {
                get
                {
                    return _ceduladeciudadaniaInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The CedulaDeCiudadania item info.
            /// </summary>
            [RepositoryItemInfo("2a0146fb-9200-4ef3-a46c-4e814ad0025c")]
            public virtual RepoItemInfo CedulaDeCiudadaniaInfo
            {
                get
                {
                    return _ceduladeciudadaniaInfo;
                }
            }

            /// <summary>
            /// The PruebasYeraldin item.
            /// </summary>
            [RepositoryItem("43c405d2-5f59-4145-a96e-16f8b2058a1e")]
            public virtual Ranorex.Text PruebasYeraldin
            {
                get
                {
                    return _pruebasyeraldinInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PruebasYeraldin item info.
            /// </summary>
            [RepositoryItemInfo("43c405d2-5f59-4145-a96e-16f8b2058a1e")]
            public virtual RepoItemInfo PruebasYeraldinInfo
            {
                get
                {
                    return _pruebasyeraldinInfo;
                }
            }

            /// <summary>
            /// The Content folder.
            /// </summary>
            [RepositoryFolder("0dba6da4-b506-49d7-9b19-7e692796073a")]
            public virtual AsesorEnLineaAndroidRepositoryFolders.ContentFolder Content
            {
                get { return _content; }
            }
        }

        /// <summary>
        /// The ContentFolder folder.
        /// </summary>
        [RepositoryFolder("0dba6da4-b506-49d7-9b19-7e692796073a")]
        public partial class ContentFolder : RepoGenBaseFolder
        {
            RepoItemInfo _numerodocumentotxtInfo;
            RepoItemInfo _nombretxtInfo;
            RepoItemInfo _tipodocumentolistInfo;
            RepoItemInfo _emailtxtInfo;
            RepoItemInfo _tipoasesorialistInfo;
            RepoItemInfo _ingresarbtnInfo;

            /// <summary>
            /// Creates a new Content  folder.
            /// </summary>
            public ContentFolder(RepoGenBaseFolder parentFolder) :
                    base("Content", "form[@title='ActivityLogin']/androidelement[@rid='content']", parentFolder, 30000, null, false, "0dba6da4-b506-49d7-9b19-7e692796073a", "")
            {
                _numerodocumentotxtInfo = new RepoItemInfo(this, "NumeroDocumentoTxt", ".//androidelement[@rid='textInputLayout']/?/?/text[@rid='editDocumento']", 30000, null, "1e39c188-7a4a-4b6b-970b-f93be16e7e37");
                _nombretxtInfo = new RepoItemInfo(this, "NombreTxt", ".//androidelement[@rid='textInputLayout2']/?/?/text[@rid='editName']", 30000, null, "6d1a9744-1aa4-4c3e-b75e-9b1c6329a8fa");
                _tipodocumentolistInfo = new RepoItemInfo(this, "TipoDocumentoList", ".//container[@rid='linearLayout4']/combobox[@rid='spTipoDocumento']", 30000, null, "11d754a9-d9ee-4fad-aab6-5fa8aa0050f4");
                _emailtxtInfo = new RepoItemInfo(this, "EmailTxt", "?/?/container[@containertype='Relative']//text[@rid='edit_email']", 30000, null, "b419efef-b10b-4b04-8f7b-318da66787f2");
                _tipoasesorialistInfo = new RepoItemInfo(this, "TipoAsesoriaList", ".//container[@rid='linearLayout5']/combobox[@rid='spTipoAsesor']", 30000, null, "005b41d7-bde7-4cfb-9cfa-09371b32c431");
                _ingresarbtnInfo = new RepoItemInfo(this, "IngresarBtn", ".//button[@resourceid='R.string.ingresar']", 30000, null, "8cf3c780-13bc-45a6-a78f-c523f183c929");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0dba6da4-b506-49d7-9b19-7e692796073a")]
            public virtual Ranorex.AndroidElement Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.AndroidElement>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0dba6da4-b506-49d7-9b19-7e692796073a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The NumeroDocumentoTxt item.
            /// </summary>
            [RepositoryItem("1e39c188-7a4a-4b6b-970b-f93be16e7e37")]
            public virtual Ranorex.Text NumeroDocumentoTxt
            {
                get
                {
                    return _numerodocumentotxtInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The NumeroDocumentoTxt item info.
            /// </summary>
            [RepositoryItemInfo("1e39c188-7a4a-4b6b-970b-f93be16e7e37")]
            public virtual RepoItemInfo NumeroDocumentoTxtInfo
            {
                get
                {
                    return _numerodocumentotxtInfo;
                }
            }

            /// <summary>
            /// The NombreTxt item.
            /// </summary>
            [RepositoryItem("6d1a9744-1aa4-4c3e-b75e-9b1c6329a8fa")]
            public virtual Ranorex.Text NombreTxt
            {
                get
                {
                    return _nombretxtInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The NombreTxt item info.
            /// </summary>
            [RepositoryItemInfo("6d1a9744-1aa4-4c3e-b75e-9b1c6329a8fa")]
            public virtual RepoItemInfo NombreTxtInfo
            {
                get
                {
                    return _nombretxtInfo;
                }
            }

            /// <summary>
            /// The TipoDocumentoList item.
            /// </summary>
            [RepositoryItem("11d754a9-d9ee-4fad-aab6-5fa8aa0050f4")]
            public virtual Ranorex.ComboBox TipoDocumentoList
            {
                get
                {
                    return _tipodocumentolistInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The TipoDocumentoList item info.
            /// </summary>
            [RepositoryItemInfo("11d754a9-d9ee-4fad-aab6-5fa8aa0050f4")]
            public virtual RepoItemInfo TipoDocumentoListInfo
            {
                get
                {
                    return _tipodocumentolistInfo;
                }
            }

            /// <summary>
            /// The EmailTxt item.
            /// </summary>
            [RepositoryItem("b419efef-b10b-4b04-8f7b-318da66787f2")]
            public virtual Ranorex.Text EmailTxt
            {
                get
                {
                    return _emailtxtInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EmailTxt item info.
            /// </summary>
            [RepositoryItemInfo("b419efef-b10b-4b04-8f7b-318da66787f2")]
            public virtual RepoItemInfo EmailTxtInfo
            {
                get
                {
                    return _emailtxtInfo;
                }
            }

            /// <summary>
            /// The TipoAsesoriaList item.
            /// </summary>
            [RepositoryItem("005b41d7-bde7-4cfb-9cfa-09371b32c431")]
            public virtual Ranorex.ComboBox TipoAsesoriaList
            {
                get
                {
                    return _tipoasesorialistInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The TipoAsesoriaList item info.
            /// </summary>
            [RepositoryItemInfo("005b41d7-bde7-4cfb-9cfa-09371b32c431")]
            public virtual RepoItemInfo TipoAsesoriaListInfo
            {
                get
                {
                    return _tipoasesorialistInfo;
                }
            }

            /// <summary>
            /// The IngresarBtn item.
            /// </summary>
            [RepositoryItem("8cf3c780-13bc-45a6-a78f-c523f183c929")]
            public virtual Ranorex.Button IngresarBtn
            {
                get
                {
                    return _ingresarbtnInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The IngresarBtn item info.
            /// </summary>
            [RepositoryItemInfo("8cf3c780-13bc-45a6-a78f-c523f183c929")]
            public virtual RepoItemInfo IngresarBtnInfo
            {
                get
                {
                    return _ingresarbtnInfo;
                }
            }
        }

        /// <summary>
        /// The CerrarSesionFolder folder.
        /// </summary>
        [RepositoryFolder("61b58625-db67-4f9d-9dd1-ed80412a87f9")]
        public partial class CerrarSesionFolder : RepoGenBaseFolder
        {
            RepoItemInfo _menuhamburguesaInfo;
            RepoItemInfo _cerrarsesionbtnInfo;

            /// <summary>
            /// Creates a new CerrarSesion  folder.
            /// </summary>
            public CerrarSesionFolder(RepoGenBaseFolder parentFolder) :
                    base("CerrarSesion", "", parentFolder, 30000, null, false, "61b58625-db67-4f9d-9dd1-ed80412a87f9", "")
            {
                _menuhamburguesaInfo = new RepoItemInfo(this, "MenuHamburguesa", "form[@title='HomeActivity']/androidelement[@rid='content']/androidelement[@rid='drawer_layout']//button[@contentdescription='Open navigation drawer']", 30000, null, "7ca42c7f-a551-4dc1-b258-37e7aa0b6b99");
                _cerrarsesionbtnInfo = new RepoItemInfo(this, "CerrarSesionBtn", "form[@title='HomeActivity']/androidelement[@rid='content']/?/?/androidelement[@rid='nav_view']//radiobutton[@resourceid='R.string.close_session']", 30000, null, "29b69c1c-0264-4b92-82c6-c35e0ac5727c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("61b58625-db67-4f9d-9dd1-ed80412a87f9")]
            public virtual Ranorex.MobileApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MobileApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("61b58625-db67-4f9d-9dd1-ed80412a87f9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MenuHamburguesa item.
            /// </summary>
            [RepositoryItem("7ca42c7f-a551-4dc1-b258-37e7aa0b6b99")]
            public virtual Ranorex.Button MenuHamburguesa
            {
                get
                {
                    return _menuhamburguesaInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MenuHamburguesa item info.
            /// </summary>
            [RepositoryItemInfo("7ca42c7f-a551-4dc1-b258-37e7aa0b6b99")]
            public virtual RepoItemInfo MenuHamburguesaInfo
            {
                get
                {
                    return _menuhamburguesaInfo;
                }
            }

            /// <summary>
            /// The CerrarSesionBtn item.
            /// </summary>
            [RepositoryItem("29b69c1c-0264-4b92-82c6-c35e0ac5727c")]
            public virtual Ranorex.RadioButton CerrarSesionBtn
            {
                get
                {
                    return _cerrarsesionbtnInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The CerrarSesionBtn item info.
            /// </summary>
            [RepositoryItemInfo("29b69c1c-0264-4b92-82c6-c35e0ac5727c")]
            public virtual RepoItemInfo CerrarSesionBtnInfo
            {
                get
                {
                    return _cerrarsesionbtnInfo;
                }
            }
        }

        /// <summary>
        /// The AsignarCitaFolder folder.
        /// </summary>
        [RepositoryFolder("db09b4e7-a812-4fc9-9f65-f52e7d80dd0e")]
        public partial class AsignarCitaFolder : RepoGenBaseFolder
        {
            RepoItemInfo _consultarcitabtnInfo;
            RepoItemInfo _areaagendaInfo;
            RepoItemInfo _aceptarcitabtnInfo;
            RepoItemInfo _asignarcitabtnInfo;

            /// <summary>
            /// Creates a new AsignarCita  folder.
            /// </summary>
            public AsignarCitaFolder(RepoGenBaseFolder parentFolder) :
                    base("AsignarCita", "", parentFolder, 30000, null, false, "db09b4e7-a812-4fc9-9f65-f52e7d80dd0e", "")
            {
                _consultarcitabtnInfo = new RepoItemInfo(this, "ConsultarCitaBtn", "form[@title='HomeActivity']/androidelement[@rid='content']//container[@rid='content_home']/container/container[@containertype='Linear']/container[3]/button[@resourceid='R.string.consult_appointment']", 30000, null, "58c5d731-875c-490f-aa1b-c02d482efaf4");
                _areaagendaInfo = new RepoItemInfo(this, "AreaAgenda", "form[@title='CalendarActivity']/androidelement/container[@containertype='Linear']/container[3]", 30000, null, "db98d6da-6e20-403c-9e6a-5a7e3d82ea7d");
                _aceptarcitabtnInfo = new RepoItemInfo(this, "AceptarCitaBtn", "form[@title='Confirmar cita']/container[@rid='content']//button[@resourceid='R.string.done']", 30000, null, "e4aef758-6796-48f5-8c98-3cf714fed0ed");
                _asignarcitabtnInfo = new RepoItemInfo(this, "AsignarCitaBtn", "form[@title='CalendarActivity']/androidelement/container[@containertype='Linear']/container[3]/?/?/androidelement[@rid='rv_appointment']/container[2]/container/container[2]", 30000, null, "d1b020d0-6f51-4252-bc45-ec64e9c72e2d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("db09b4e7-a812-4fc9-9f65-f52e7d80dd0e")]
            public virtual Ranorex.MobileApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MobileApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("db09b4e7-a812-4fc9-9f65-f52e7d80dd0e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ConsultarCitaBtn item.
            /// </summary>
            [RepositoryItem("58c5d731-875c-490f-aa1b-c02d482efaf4")]
            public virtual Ranorex.Button ConsultarCitaBtn
            {
                get
                {
                    return _consultarcitabtnInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ConsultarCitaBtn item info.
            /// </summary>
            [RepositoryItemInfo("58c5d731-875c-490f-aa1b-c02d482efaf4")]
            public virtual RepoItemInfo ConsultarCitaBtnInfo
            {
                get
                {
                    return _consultarcitabtnInfo;
                }
            }

            /// <summary>
            /// The AreaAgenda item.
            /// </summary>
            [RepositoryItem("db98d6da-6e20-403c-9e6a-5a7e3d82ea7d")]
            public virtual Ranorex.Container AreaAgenda
            {
                get
                {
                    return _areaagendaInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The AreaAgenda item info.
            /// </summary>
            [RepositoryItemInfo("db98d6da-6e20-403c-9e6a-5a7e3d82ea7d")]
            public virtual RepoItemInfo AreaAgendaInfo
            {
                get
                {
                    return _areaagendaInfo;
                }
            }

            /// <summary>
            /// The AceptarCitaBtn item.
            /// </summary>
            [RepositoryItem("e4aef758-6796-48f5-8c98-3cf714fed0ed")]
            public virtual Ranorex.Button AceptarCitaBtn
            {
                get
                {
                    return _aceptarcitabtnInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AceptarCitaBtn item info.
            /// </summary>
            [RepositoryItemInfo("e4aef758-6796-48f5-8c98-3cf714fed0ed")]
            public virtual RepoItemInfo AceptarCitaBtnInfo
            {
                get
                {
                    return _aceptarcitabtnInfo;
                }
            }

            /// <summary>
            /// The AsignarCitaBtn item.
            /// </summary>
            [RepositoryItem("d1b020d0-6f51-4252-bc45-ec64e9c72e2d")]
            public virtual Ranorex.Container AsignarCitaBtn
            {
                get
                {
                    return _asignarcitabtnInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The AsignarCitaBtn item info.
            /// </summary>
            [RepositoryItemInfo("d1b020d0-6f51-4252-bc45-ec64e9c72e2d")]
            public virtual RepoItemInfo AsignarCitaBtnInfo
            {
                get
                {
                    return _asignarcitabtnInfo;
                }
            }
        }

        /// <summary>
        /// The ReasignarCitaFolder folder.
        /// </summary>
        [RepositoryFolder("6ef510b0-d838-486b-ba36-257411c55bce")]
        public partial class ReasignarCitaFolder : RepoGenBaseFolder
        {
            RepoItemInfo _citaInfo;
            RepoItemInfo _reasignarcitabtnInfo;
            RepoItemInfo _citahorario2Info;
            RepoItemInfo _aceptarreasignarcitaInfo;

            /// <summary>
            /// Creates a new ReasignarCita  folder.
            /// </summary>
            public ReasignarCitaFolder(RepoGenBaseFolder parentFolder) :
                    base("ReasignarCita", "", parentFolder, 30000, null, false, "6ef510b0-d838-486b-ba36-257411c55bce", "")
            {
                _citaInfo = new RepoItemInfo(this, "Cita", "form[@title='HomeActivity']//container[@rid='content_home']/container/container[@containertype='Linear']/container[4]/container[@rid='layout_appointments']/androidelement[@rid='rv_appointment_assigned']//container[@rid='rowFG']/container[@rid='appointment_delete']/container[1]", 30000, null, "9db9b3a0-8991-4b71-ba9d-912e0e9f58be");
                _reasignarcitabtnInfo = new RepoItemInfo(this, "ReasignarCitaBtn", "form[@title='(none)']/?/?/container[@rid='container']/?/?/container[@rid='design_bottom_sheet']/?/?/button[@resourceid='R.string.reasignar_cita']", 30000, null, "9b7cac09-c138-453d-9508-3762e62c4f1e");
                _citahorario2Info = new RepoItemInfo(this, "CitaHorario2", "form[@title='CalendarActivity']/androidelement[@rid='content']/container/container[3]/?/?/androidelement[@rid='rv_appointment']/container[2]/container[@containertype='Linear']/container[2]/text[@rid='assign_appointment']", 30000, null, "0db09d49-f5a0-41eb-8c31-ecffa457824f");
                _aceptarreasignarcitaInfo = new RepoItemInfo(this, "AceptarReasignarCita", "form[@title='Reasignar cita']/container[@rid='content']//button[@resourceid='R.string.done']", 30000, null, "6d562b4c-8c71-4283-8d93-a720997b52a7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6ef510b0-d838-486b-ba36-257411c55bce")]
            public virtual Ranorex.MobileApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MobileApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6ef510b0-d838-486b-ba36-257411c55bce")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Cita item.
            /// </summary>
            [RepositoryItem("9db9b3a0-8991-4b71-ba9d-912e0e9f58be")]
            public virtual Ranorex.Container Cita
            {
                get
                {
                    return _citaInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Cita item info.
            /// </summary>
            [RepositoryItemInfo("9db9b3a0-8991-4b71-ba9d-912e0e9f58be")]
            public virtual RepoItemInfo CitaInfo
            {
                get
                {
                    return _citaInfo;
                }
            }

            /// <summary>
            /// The ReasignarCitaBtn item.
            /// </summary>
            [RepositoryItem("9b7cac09-c138-453d-9508-3762e62c4f1e")]
            public virtual Ranorex.Button ReasignarCitaBtn
            {
                get
                {
                    return _reasignarcitabtnInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ReasignarCitaBtn item info.
            /// </summary>
            [RepositoryItemInfo("9b7cac09-c138-453d-9508-3762e62c4f1e")]
            public virtual RepoItemInfo ReasignarCitaBtnInfo
            {
                get
                {
                    return _reasignarcitabtnInfo;
                }
            }

            /// <summary>
            /// The CitaHorario2 item.
            /// </summary>
            [RepositoryItem("0db09d49-f5a0-41eb-8c31-ecffa457824f")]
            public virtual Ranorex.Text CitaHorario2
            {
                get
                {
                    return _citahorario2Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The CitaHorario2 item info.
            /// </summary>
            [RepositoryItemInfo("0db09d49-f5a0-41eb-8c31-ecffa457824f")]
            public virtual RepoItemInfo CitaHorario2Info
            {
                get
                {
                    return _citahorario2Info;
                }
            }

            /// <summary>
            /// The AceptarReasignarCita item.
            /// </summary>
            [RepositoryItem("6d562b4c-8c71-4283-8d93-a720997b52a7")]
            public virtual Ranorex.Button AceptarReasignarCita
            {
                get
                {
                    return _aceptarreasignarcitaInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AceptarReasignarCita item info.
            /// </summary>
            [RepositoryItemInfo("6d562b4c-8c71-4283-8d93-a720997b52a7")]
            public virtual RepoItemInfo AceptarReasignarCitaInfo
            {
                get
                {
                    return _aceptarreasignarcitaInfo;
                }
            }
        }

        /// <summary>
        /// The EliminarCitaFolder folder.
        /// </summary>
        [RepositoryFolder("1786513e-6ce3-4984-92f0-b5cb5345d266")]
        public partial class EliminarCitaFolder : RepoGenBaseFolder
        {
            RepoItemInfo _areacitaInfo;
            RepoItemInfo _eliminarcitamenuInfo;
            RepoItemInfo _aceptareliminarInfo;
            RepoItemInfo _eliminarcitaInfo;

            /// <summary>
            /// Creates a new EliminarCita  folder.
            /// </summary>
            public EliminarCitaFolder(RepoGenBaseFolder parentFolder) :
                    base("EliminarCita", "", parentFolder, 30000, null, false, "1786513e-6ce3-4984-92f0-b5cb5345d266", "")
            {
                _areacitaInfo = new RepoItemInfo(this, "AreaCita", "form[@title='HomeActivity']//container[@rid='content_home']/container/container[@containertype='Linear']/container[4]/container[@rid='layout_appointments']/androidelement[@rid='rv_appointment_assigned']//container[@rid='rowFG']/container[@rid='appointment_delete']", 30000, null, "02357a99-3f72-4cdf-8d45-9f1cf44791f3");
                _eliminarcitamenuInfo = new RepoItemInfo(this, "EliminarCitaMEnu", "form[@title='(none)']/?/?/container[@rid='container']/?/?/container[@rid='design_bottom_sheet']/?/?/button[@resourceid='R.string.delete_appointment']", 30000, null, "f2c0d330-be17-4abe-ba73-bc85555edf82");
                _aceptareliminarInfo = new RepoItemInfo(this, "AceptarEliminar", "form[@title='Eliminar cita']/container[@rid='content']//button[@resourceid='R.string.done']", 30000, null, "56ee8c11-dae0-4e51-ab8d-9281a97b7719");
                _eliminarcitaInfo = new RepoItemInfo(this, "EliminarCita", "form[@title='HomeActivity']//container[@rid='content_home']/container/container[@containertype='Linear']/container[4]/container[@rid='layout_appointments']/androidelement[@rid='rv_appointment_assigned']//container[@rid='rowBG']/container[@rid='delete']/container[@containertype='Linear']", 30000, null, "8c905282-1a1d-4c2d-993f-97ce1e285a97");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1786513e-6ce3-4984-92f0-b5cb5345d266")]
            public virtual Ranorex.MobileApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MobileApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1786513e-6ce3-4984-92f0-b5cb5345d266")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AreaCita item.
            /// </summary>
            [RepositoryItem("02357a99-3f72-4cdf-8d45-9f1cf44791f3")]
            public virtual Ranorex.Container AreaCita
            {
                get
                {
                    return _areacitaInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The AreaCita item info.
            /// </summary>
            [RepositoryItemInfo("02357a99-3f72-4cdf-8d45-9f1cf44791f3")]
            public virtual RepoItemInfo AreaCitaInfo
            {
                get
                {
                    return _areacitaInfo;
                }
            }

            /// <summary>
            /// The EliminarCitaMEnu item.
            /// </summary>
            [RepositoryItem("f2c0d330-be17-4abe-ba73-bc85555edf82")]
            public virtual Ranorex.Button EliminarCitaMEnu
            {
                get
                {
                    return _eliminarcitamenuInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The EliminarCitaMEnu item info.
            /// </summary>
            [RepositoryItemInfo("f2c0d330-be17-4abe-ba73-bc85555edf82")]
            public virtual RepoItemInfo EliminarCitaMEnuInfo
            {
                get
                {
                    return _eliminarcitamenuInfo;
                }
            }

            /// <summary>
            /// The AceptarEliminar item.
            /// </summary>
            [RepositoryItem("56ee8c11-dae0-4e51-ab8d-9281a97b7719")]
            public virtual Ranorex.Button AceptarEliminar
            {
                get
                {
                    return _aceptareliminarInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AceptarEliminar item info.
            /// </summary>
            [RepositoryItemInfo("56ee8c11-dae0-4e51-ab8d-9281a97b7719")]
            public virtual RepoItemInfo AceptarEliminarInfo
            {
                get
                {
                    return _aceptareliminarInfo;
                }
            }

            /// <summary>
            /// The EliminarCita item.
            /// </summary>
            [RepositoryItem("8c905282-1a1d-4c2d-993f-97ce1e285a97")]
            public virtual Ranorex.Container EliminarCita
            {
                get
                {
                    return _eliminarcitaInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The EliminarCita item info.
            /// </summary>
            [RepositoryItemInfo("8c905282-1a1d-4c2d-993f-97ce1e285a97")]
            public virtual RepoItemInfo EliminarCitaInfo
            {
                get
                {
                    return _eliminarcitaInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
