///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AsesorEnLineaAndroid
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AsignarCita recording.
    /// </summary>
    [TestModule("9ee3e4e3-cd9d-4808-9714-09721c533f8a", ModuleType.Recording, 1)]
    public partial class AsignarCita : ITestModule
    {
        /// <summary>
        /// Holds an instance of the AsesorEnLineaAndroidRepository repository.
        /// </summary>
        public static AsesorEnLineaAndroidRepository repo = AsesorEnLineaAndroidRepository.Instance;

        static AsignarCita instance = new AsignarCita();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AsignarCita()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AsignarCita Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComProteccionVideoasesoria.AsignarCita.ConsultarCitaBtn' at Center", repo.ComProteccionVideoasesoria.AsignarCita.ConsultarCitaBtnInfo, new RecordItemIndex(0));
            repo.ComProteccionVideoasesoria.AsignarCita.ConsultarCitaBtn.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Up (270°)' starting from 'Center' with distance '2.0' with swipe duration'500ms' and step count '0' on item 'ComProteccionVideoasesoria.AsignarCita.AreaAgenda'.", repo.ComProteccionVideoasesoria.AsignarCita.AreaAgendaInfo, new RecordItemIndex(1));
            repo.ComProteccionVideoasesoria.AsignarCita.AreaAgenda.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Up (270°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "2.0"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "500ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComProteccionVideoasesoria.AsignarCita.AsignarCitaBtn' at Center", repo.ComProteccionVideoasesoria.AsignarCita.AsignarCitaBtnInfo, new RecordItemIndex(2));
            repo.ComProteccionVideoasesoria.AsignarCita.AsignarCitaBtn.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComProteccionVideoasesoria.AsignarCita.AceptarCitaBtn' at Center", repo.ComProteccionVideoasesoria.AsignarCita.AceptarCitaBtnInfo, new RecordItemIndex(3));
            repo.ComProteccionVideoasesoria.AsignarCita.AceptarCitaBtn.Touch();
            Delay.Milliseconds(500);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
