///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AsesorEnLineaAndroid
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EliminarCita recording.
    /// </summary>
    [TestModule("b552a4ed-2ee8-4b54-bca4-21d3c7cf6420", ModuleType.Recording, 1)]
    public partial class EliminarCita : ITestModule
    {
        /// <summary>
        /// Holds an instance of the AsesorEnLineaAndroidRepository repository.
        /// </summary>
        public static AsesorEnLineaAndroidRepository repo = AsesorEnLineaAndroidRepository.Instance;

        static EliminarCita instance = new EliminarCita();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EliminarCita()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EliminarCita Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Touch gestures", "Swipe gesture with direction 'Left (180°)' starting from 'Center' with distance '1.0' with swipe duration'500ms' and step count '0' on item 'ComProteccionVideoasesoria.EliminarCita.AreaCita'.", repo.ComProteccionVideoasesoria.EliminarCita.AreaCitaInfo, new RecordItemIndex(0));
            repo.ComProteccionVideoasesoria.EliminarCita.AreaCita.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Left (180°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "1.0"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "500ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComProteccionVideoasesoria.EliminarCita.EliminarCita' at Center", repo.ComProteccionVideoasesoria.EliminarCita.EliminarCitaInfo, new RecordItemIndex(1));
            repo.ComProteccionVideoasesoria.EliminarCita.EliminarCita.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComProteccionVideoasesoria.EliminarCita.AceptarEliminar' at Center", repo.ComProteccionVideoasesoria.EliminarCita.AceptarEliminarInfo, new RecordItemIndex(2));
            repo.ComProteccionVideoasesoria.EliminarCita.AceptarEliminar.Touch();
            Delay.Milliseconds(500);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
