///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AsesorEnLineaAndroid
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The IniciarSesion recording.
    /// </summary>
    [TestModule("1c4e226d-283c-4493-a71b-d61e1b5789c6", ModuleType.Recording, 1)]
    public partial class IniciarSesion : ITestModule
    {
        /// <summary>
        /// Holds an instance of the AsesorEnLineaAndroidRepository repository.
        /// </summary>
        public static AsesorEnLineaAndroidRepository repo = AsesorEnLineaAndroidRepository.Instance;

        static IniciarSesion instance = new IniciarSesion();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public IniciarSesion()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static IniciarSesion Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run mobile app 'com.proteccion.videoasesoria' on device 'ASUS_Z01BDC'.", new RecordItemIndex(0));
            Host.Local.RunMobileApp("ASUS_Z01BDC", "com.proteccion.videoasesoria", true);
            Delay.Milliseconds(3500);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to 'Yeraldin Cano' on item 'ComProteccionVideoasesoria.Login.Content.NombreTxt'.", repo.ComProteccionVideoasesoria.Login.Content.NombreTxtInfo, new RecordItemIndex(1));
            repo.ComProteccionVideoasesoria.Login.Content.NombreTxt.Element.SetAttributeValue("Text", "Yeraldin Cano");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComProteccionVideoasesoria.Login.Content.TipoDocumentoList' at Center", repo.ComProteccionVideoasesoria.Login.Content.TipoDocumentoListInfo, new RecordItemIndex(2));
            repo.ComProteccionVideoasesoria.Login.Content.TipoDocumentoList.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComProteccionVideoasesoria.Login.CedulaDeCiudadania' at Center", repo.ComProteccionVideoasesoria.Login.CedulaDeCiudadaniaInfo, new RecordItemIndex(3));
            repo.ComProteccionVideoasesoria.Login.CedulaDeCiudadania.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '1020483046' on item 'ComProteccionVideoasesoria.Login.Content.NumeroDocumentoTxt'.", repo.ComProteccionVideoasesoria.Login.Content.NumeroDocumentoTxtInfo, new RecordItemIndex(4));
            repo.ComProteccionVideoasesoria.Login.Content.NumeroDocumentoTxt.Element.SetAttributeValue("Text", "1020483046");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to 'yeraldin.ig2019@gmail.com' on item 'ComProteccionVideoasesoria.Login.Content.EmailTxt'.", repo.ComProteccionVideoasesoria.Login.Content.EmailTxtInfo, new RecordItemIndex(5));
            repo.ComProteccionVideoasesoria.Login.Content.EmailTxt.Element.SetAttributeValue("Text", "yeraldin.ig2019@gmail.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComProteccionVideoasesoria.Login.Content.TipoAsesoriaList' at Center", repo.ComProteccionVideoasesoria.Login.Content.TipoAsesoriaListInfo, new RecordItemIndex(6));
            repo.ComProteccionVideoasesoria.Login.Content.TipoAsesoriaList.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComProteccionVideoasesoria.Login.PruebasYeraldin' at Center", repo.ComProteccionVideoasesoria.Login.PruebasYeraldinInfo, new RecordItemIndex(7));
            repo.ComProteccionVideoasesoria.Login.PruebasYeraldin.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComProteccionVideoasesoria.Login.Content.IngresarBtn' at Center", repo.ComProteccionVideoasesoria.Login.Content.IngresarBtnInfo, new RecordItemIndex(8));
            repo.ComProteccionVideoasesoria.Login.Content.IngresarBtn.Touch();
            Delay.Milliseconds(500);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
